### ISSUE TITLE
Delete Feature

### ISSUE THREAD

**Issue by hmert** [okulbilisim/ojs#1372] opened 2015-12-22 14:15 UTC
- [x] Journal
- [x] Issue
- [x] Article

**Comment by beyzakokcan** [comment] 2015-12-25 12:20
enough

**Comment by utkuaydin** [comment] 2015-12-25 12:22
It would be great if you could test these to see if they are working as intended while we are in the beta stage.

**Comment by beyzakokcan** [comment] 2015-12-25 12:27
of course. I always test :)

**Comment by beyzakokcan** [comment] 2015-12-25 12:28
user and journal are not our priority right now. You can close the issue after testing. We can go back to user and journal later.

**Comment by utkuaydin** [comment] 2015-12-25 12:29
Journal is already done. I'll leave user deletion for later.

**Comment by beyzakokcan** [comment] 2015-12-25 12:33
Great. Thank you.

**Closed** 2015-12-29 19:57 UTC
Labels: Critical, Feature
